
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bancoRedes2
      - DB_USER=postgres
      - DB_PASSWORD=12345
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bancoRedes2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: